---
title: "R: Functions and Packages"
subtitle: "Part 1: Overview and Introduction"
author: "Mik Black"
date: "2 February 2016"
output: ioslides_presentation
---

## Overview - what will we cover?

 - Writing functions in R
 - R package construction (basic)
 - R package anatomy
 - R packages distribution
 - Testing

## Aside - some awesomeness

 - Karl Broman's ([\@kwbroman](https://twitter.com/kwbroman)) "Tools for Reproducible Research" course is awesome:
 
    http://kbroman.org/Tools4RR/
    
    https://github.com/kbroman
 
 - Many of the things we'll talk about her have been borrowed from Karl's excellent lectures.
 
## Another aside - packages to install

 - Later in the lesson we'll be using the following R packages:
    - `devtools`
    - `roxygen`
 - These can be installed via:

```{r, eval=FALSE}
install.packages('devtools')
library("devtools")
devtools::install_github("klutometis/roxygen")
```

 - Maybe fire up RStudio and do this now, to avoid a logjam later...
 
## Introduction - functions

 - In R, internal and library functions provide users with access to powerful analytic tools.
 - These functions form the basis of much of our own code: we use functions written by others in a way that helps us achieve our own analysis goals.
 - Even relatively inexperienced R users are fairly quick to adopt the idea of loading packages to gain access to powerful collections of functions.
 
## Writing our own functions

 - Despite our love of other people's functions, it often takes R users a while to start writing their own functions, despite there being a number of benefits:
    - better code organisation
    - less code re-writing (e.g., copy and paste)
    - better ability to test, debug and document
    - improved sharing
 
## Why don't we do it more?

 - Time: it takes extra time to turn something into a function (but not much).
 - Workflow: R code is often written as part of an exploratory data analysis process - it is being driven by ideas about the analysis we are performing and the question we ask along the way.
 - Focus: R users are generally not trained programmers - our focus is on using code to achieve a goal, and that goal is not to create "elegant, well-written, re-usable" code.  It is generally about trying to answer a scientific question.
 
## Why SHOULD we write functions?

 - I am not even going to tell you how many times I have typed the same code across different projects...  
 - Turning frequently used code into a collection of functions will save you time
 - It will also improve the readability, flow and organisation of your code.
 - And once you get into the habit of creating your own functions, it will make you a better programmer.
 
## Packages

 - Once you've written some functions that you use regularly, it is a simple step to turn them into a package.
  - Once installed, your functions are always available in R.
  - Makes software maintenance/improvement easier - all code and documentation stays in one place (I am guilty of having multiple versions of files containing different versions of the same function living all over my laptop)
  - Makes sharing easier - others can use your functions by simply installing your package.
  
## Resources

 - Hadley Wickham ([\@hadleywickham](https://twitter.com/hadleywickham)) has produced some excellent material on coding style and package creation:
    - Programming: http://adv-r.had.co.nz/
    - Packages: http://r-pkgs.had.co.nz/
 
## Lets write some functions....

 - We'll use the Software Carpentry material on writing functions as a quick refresher:
 
  http://swcarpentry.github.io/r-novice-inflammation/02-func-R.html
 
 
